using Zonit.Extensions.Tenants.Settings;

namespace Zonit.Extensions.Tenants;

/// <summary>
/// Read-only API for consumers (Razor pages, layouts, components) that need the
/// resolved tenant and its hydrated <see cref="Setting{T}"/> models. Plugins that ship
/// their own <see cref="Setting{T}"/> derivatives consume them via
/// <see cref="GetSetting{T}"/> from the same surface.
/// </summary>
/// <remarks>
/// <para><b>Strongly-typed access.</b> Built-in settings are exposed via the
/// auto-generated <see cref="TenantSettings"/> object — <c>provider.Settings.Site.Title</c>,
/// <c>provider.Settings.Theme.PrimaryColor</c> etc. The source generator emits one
/// property per <see cref="Setting{T}"/> visible at compile time.</para>
///
/// <para><b>Open-typed access.</b> Plugins that prefer not to extend
/// <see cref="TenantSettings"/> (or that resolve settings dynamically) call
/// <see cref="GetSetting{T}"/> with their concrete <see cref="Setting{T}"/> type.</para>
/// </remarks>
public interface ITenantProvider
{
    /// <summary>The resolved tenant for the current scope, or <see langword="null"/> when none was matched.</summary>
    Tenant? Current { get; }

    /// <summary>
    /// Resolves a hydrated <see cref="Setting{T}"/> instance. Returns the type's compile-time
    /// defaults when the tenant has no override (or when no tenant is set).
    /// </summary>
    /// <typeparam name="TSetting">A concrete <see cref="Setting{T}"/> subtype with a parameterless ctor.</typeparam>
    TSetting GetSetting<TSetting>() where TSetting : ISetting, new();

    /// <summary>
    /// Strongly-typed accessor for built-in (and source-generator-discovered) settings.
    /// Backed by the partial <see cref="TenantSettings"/> class auto-generated by
    /// <c>Zonit.Extensions.Tenants.SourceGenerators</c>.
    /// </summary>
    TenantSettings Settings { get; }

    /// <summary>Raised when the resolved tenant changes in this scope.</summary>
    event Action? OnChange;
}
