using Zonit.Extensions.Tenants.Settings;

namespace Zonit.Extensions.Tenants;

/// <summary>
/// Read-only API for consumers (Razor pages, layouts, components) that need the
/// resolved tenant and its hydrated <see cref="Setting{T}"/> models. Plugins that ship
/// their own <see cref="Setting{T}"/> derivatives consume them via
/// <see cref="GetSetting{T}"/> from the same surface.
/// </summary>
/// <remarks>
/// <para><b>Strongly-typed access.</b> Built-in settings are exposed via the
/// auto-generated <see cref="TenantSettings"/> object — <c>provider.Settings.Site.Title</c>,
/// <c>provider.Settings.Theme.PrimaryColor</c> etc. The source generator emits one
/// property per <see cref="Setting{T}"/> visible at compile time.</para>
///
/// <para><b>Open-typed access.</b> Plugins that prefer not to extend
/// <see cref="TenantSettings"/> (or that resolve settings dynamically) call
/// <see cref="GetSetting{T}"/> with their concrete <see cref="Setting{T}"/> type.</para>
/// </remarks>
public interface ITenantProvider
{
    /// <summary>
    /// The resolved tenant for this scope, or <see langword="null"/> when none was resolved.
    /// </summary>
    /// <remarks>
    /// <para><b>Nullable on purpose.</b> This property carries identity — <c>Id</c>,
    /// <c>Domain</c>, <c>Variables</c> — and none of those has a meaningful value when no tenant
    /// was resolved. Handing back a sentinel would make <c>@Tenant.Current.Domain</c> render
    /// <c>"*"</c> and <c>Current.Id</c> read <see cref="Guid.Empty"/>, which is worse than a
    /// compiler error: the page displays something, and the something is wrong.</para>
    ///
    /// <para><b>Reading settings does not go through here</b> and never needs a null check —
    /// <see cref="Settings"/> and <see cref="GetSetting{TSetting}"/> always resolve, falling back
    /// to configuration and then to compile-time defaults. So the null only surfaces where it is
    /// genuinely a question, and <see cref="Resolution"/> answers *why* it is null.</para>
    /// </remarks>
    Tenant? Current { get; }

    /// <summary>
    /// Why <see cref="Current"/> holds what it holds.
    /// </summary>
    /// <remarks>
    /// A single-site host can ignore this. A multi-domain host should not: without it,
    /// <see cref="TenantResolution.Unknown"/> — a hostname pointed at the app with no tenant
    /// behind it — is indistinguishable from a deliberate single-site setup, and the app serves
    /// default branding on a domain it does not know.
    /// <code>
    /// if (Tenants.Resolution is TenantResolution.Unknown)
    ///     return Results.NotFound();
    /// </code>
    /// </remarks>
    TenantResolution Resolution { get; }

    /// <summary>
    /// Resolves a hydrated <see cref="Setting{T}"/> instance. Returns the type's compile-time
    /// defaults when the tenant has no override (or when no tenant is set).
    /// </summary>
    /// <typeparam name="TSetting">A concrete <see cref="Setting{T}"/> subtype with a parameterless ctor.</typeparam>
    TSetting GetSetting<TSetting>() where TSetting : ISetting, new();

    /// <summary>
    /// Strongly-typed accessor for built-in (and source-generator-discovered) settings.
    /// Backed by the partial <see cref="TenantSettings"/> class auto-generated by
    /// <c>Zonit.Extensions.Tenants.SourceGenerators</c>.
    /// </summary>
    TenantSettings Settings { get; }

    /// <summary>Raised when the resolved tenant changes in this scope.</summary>
    event Action? OnChange;

    /// <summary>
    /// Raised when a persisted blob for a setting could not be hydrated. The setting still
    /// resolves — to its compile-time defaults — so subscribing is the only way to tell a
    /// corrupt override apart from "no override".
    /// </summary>
    /// <remarks>
    /// Scoped to the current provider, so a host that wants global coverage subscribes from
    /// something scoped too (middleware, a circuit-lifetime service). See
    /// <see cref="SettingHydrationFailure"/> for why this is an event rather than a log call.
    /// </remarks>
    event Action<SettingHydrationFailure>? OnSettingHydrationFailed;
}
